### ISSUE TITLE
Make the URL where the app is hosted, a config variable

### ISSUE THREAD

**Issue by hetalrach** [joshsoftware/donation_management#19]
That way, we don't have to hardcode things into the code.

**Comment by hetalrach** [comment]
I believe this is used in the email templates etc. We need to remove hardcoding, for others to be able to re-use this module.

**Comment by sethu** [comment]
Its not hardcodeed, it is in configuration file.

**Comment by hetalrach** [comment]
As discussed, it will need to be a config variable
