### ISSUE TITLE
Send SMS confirmation

### ISSUE THREAD

**Issue by sethu** [joshsoftware/donation_management#4]
Send sms confirmation once donation received, send confirmation to donor as well as donation-co-ordinator

**Comment by hetalrach** [comment]
sms text

Donor: Thanks for donation of Rs XXX/-. Your receipt will be processed manually and sent to you within a week over email.

Donotion Co-ordinator: Rs XXX/- (cash/cheque) received from <name> <number> <email>

**Comment by hetalrach** [comment]
The above comment has some part missing maybe due to some issue in the way github issues parses comments.

The SMS to Donation co-ordinator should also have the phone number of the donor. Can you please add that.
